otipl/otipl/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from otipl import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^otipl/', include('otipl.foo.urls')),
    # url(r'^otipl/(?P<slug>.*)$', 'main.views.otipl', name='otipl'),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^(?P<slug>.*)$', 'main.views.otipl', name='otipl'),
)

otipl/main/models.py
from django.db import models

from orderedmodel import OrderedModel

from django.db import models
from django.core.files.storage import FileSystemStorage

from otipl.settings import PROJECT_DIR

import os

fs = FileSystemStorage(location=os.path.join(PROJECT_DIR, "files"))

class File(models.Model):
    page = models.ForeignKey('Page')
    file = models.FileField(upload_to="file-%Y%m%d-%H%M", storage=fs)

    def __unicode__(self):
        return unicode(self.file) + " in " + unicode(self.page)

class TestModel(OrderedModel):
    name = models.CharField(max_length=30)



class Section(OrderedModel):
    name = models.CharField(max_length=30)
# 	Name
    def __unicode__(self):
        return self.name

class Page(OrderedModel):
    content = models.CharField(max_length=30000)
    name = models.CharField(max_length=30)
    slug = models.CharField(max_length=100, blank=True)
    section = models.ForeignKey(Section, blank=True, null=True)
    on_left_bar = models.BooleanField()
    get_pass_button = models.BooleanField()    
    #section = models.ForeignKey(Section)

    def __unicode__(self):
    	return (self.section.name if self.section else '') + '/' + self.name

class NewsItem(models.Model):
    header = models.CharField(max_length=200)
    content = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add = True)
    show = models.BooleanField()

    def __unicode__(self):
    	return self.header
# Create your models here.

otipl/orderedmodel/models.py
from django.db import models
from django.core.exceptions import ValidationError


class OrderedModel(models.Model):
  order = models.PositiveIntegerField(blank=True, unique=True)

  class Meta:
    abstract = True
    ordering = ['order']

  def save(self, swapping=False, *args, **kwargs):
    if not self.id:
      try:
        self.order = self.max_order() + 1
      except IndexError:
        self.order = 1 # 0 is a special index used in swap
    if self.order == 0 and not swapping:
      raise ValidationError("Can't set 'order' to 0")
    super(OrderedModel, self).save(*args, **kwargs)

  @classmethod
  def swap(cls, obj1, obj2):
    tmp, obj2.order = obj2.order, 0
    obj2.save(swapping=True)
    obj2.order, obj1.order = obj1.order, tmp
    obj1.save()
    obj2.save()

  @classmethod
  def max_order(cls):
    return cls.objects.order_by('-order')[0].order

otipl/main/views.py
from django.http import HttpResponse
from django.shortcuts import render

from models import Section, Page, NewsItem, File

from django.core.files import File as DjFile
import os
from otipl.settings import PROJECT_DIR

def make_news():
    news = NewsItem.objects.filter(show=True).order_by('-created_at')
    return ('<br>'+'.'*50).join(["<h5>%s %s</h5> %s" % (n.created_at.strftime("%d-%m-%Y"), n.header, n.content) for n in news])

def index(request, slug=''):
    sections = Section.objects.all()
    # slug = '/' + slug
    pages = Page.objects.filter(slug=slug)
    page = ''
    files = []
    if pages:
    	page = pages[0]
        files = page.file_set.all()
    dj_files = []
    for f in files:
        dj_files += [f.file]
    free_sec = Page.objects.filter(section__isnull=True)
    context = {'sections': sections, 'page': page, 'slug': slug, 'news': make_news(), 'files': dj_files, 'free_sec': free_sec}

    return render(request, 'main/index.html', context)

def otipl(request, slug=''):
    sections = Section.objects.all()
    # slug = '/' + slug
    pages = Page.objects.filter(slug=slug)
    page = ''
    files = []
    if pages:
        page = pages[0]
        files = page.file_set.all()
    dj_files = []
    for f in files:
        dj_files += [f.file]
    free_sec = Page.objects.filter(section__isnull=True,on_left_bar=False,get_pass_button=False)
    left_bar = Page.objects.filter(on_left_bar=True)
    get_pass = Page.objects.filter(get_pass_button=True)
    context = {'sections': sections, 
                'page': page, 
                'slug': slug, 
                'news': make_news(), 
                'files': dj_files, 
                'free_sec': free_sec, 
                'left_bar': left_bar,
                'get_pass_button': get_pass[0] if get_pass else ''}

    return render(request, 'main/otipl.html', context)

otipl/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Otipl</title>
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <style type="text/css">
html,
body {
  height: 100%;
  /* The html and body elements cannot have any padding or margin. */
}

/* Wrapper for page content to push down footer */
#wrap {
  min-height: 100%;
  height: auto !important;
  height: 100%;
  /* Negative indent footer by its height */
  margin: 0 auto -60px;
  /* Pad bottom by footer height */
  padding: 0 0 60px;
}

/* Set the fixed height of the footer here */
#footer {
  height: 80px;
  /*background-color: #f5f5f5;*/

}
/*#wrap > .container {
  padding: 60px 15px 0;
}*/
/*  */ .credit {
  margin: 20px 0;
}

#footer > .well {
  padding-left: 15px;
  padding-right: 15px;
}

/*code {
  font-size: 80%;
}*/
        </style>
    </head>
    <body>
        <script src="{% static "js/jquery.js" %}"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>
 <div id="wrap">
 <div class="container">
 <div class="row text-center"  style="height: 100%; min-height: 100%; vertical-align:middle">
   <div class="col-md-3 col-md-offset-2" style="height: 100px;vertical-align:middle">
      <br><br><br>
      МГУ имени М.В. Ломоносова<br>
      Филологический факультет
   </div>
   <div class="col-md-2" >
     <img src="{% static "images/logo.jpg" %}" class="img-responsive" style="padding: 5px" alt="Responsive image">
    </div>
   <div class="col-md-3">
      <br><br><br>
      Отделение теоретической<br>
      и прикладной лингвистики
   </div>
 </div>
 </div>
<!-- <div class="row">
  <div class="col-md-6 col-md-offset-3"><img src="{% static "images/logo.jpg" %}" class="img-responsive" alt="Responsive image"></div>
</div> -->
<!-- <div class="col-md-10 col-md-offset-1"> -->
        <div class="container">
          <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            
            <div class="collapse navbar-collapse text-center">
              <ul class="nav navbar-nav">
                {% for sec in sections %}

                    <li class="dropdown {% if page and page.subsection.section == sec %} active {% endif %}">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ sec.name }}<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        {% for subsec in sec.page_set.all %}
                          <li><a href="/{{subsec.slug}}">{{ subsec.name }}</a></li>
                        {% endfor %}
                      </ul>
                    </li>
                {% endfor %}
                {% for sec in free_sec %}
                    <li class=""><a href="/{{sec.slug}}">{{sec.name}}</a></li>
                {% endfor %} 
                <!-- <li class="active"><a href="#">ОТиПЛ</a></li>
                <li class=""><a href="#">Школьникам и абитуриентам</a></li>
                <li class=""><a href="#">Студентам</a></li>
                <li class=""><a href="#">Абитуриентам</a></li>
                <li class=""><a href="#">Сотрудникам и преподавателям</a></li>                            
                <li class=""><a href="#">Проекты</a></li>              
                <li class=""><a href="#">Книги</a></li>              
                <li class=""><a href="#">Ссылки</a></li>               -->
                
              </ul>
              
            </div><!-- /.navbar-collapse -->
            
          </nav>
          <div class="navbar col-md-3">
              <ul class="nav">
                <li class="active"><a href="#">ОТиПЛ</a></li>
                <li class=""><a href="#">Школьникам и абитуриентам</a></li>
                <li class=""><a href="#">Студентам</a></li>
                <li class=""><a href="#">Абитуриентам</a></li>
                <li class=""><a href="#">Сотрудникам и преподавателям</a></li>                            
                <li class=""><a href="#">Проекты</a></li>              
                <li class=""><a href="#">Книги</a></li>              
                <li class=""><a href="#">Ссылки</a></li>
                
              </ul>
              
            </div><!-- /.navbar-collapse -->
            
          </nav>
          <div class="row">
            <div class="col-md-8">
            <!-- {{page}} {{slug}} -->

            
            {{page.content|safe}}
<!--            <h5> Что такое ОТиПЛ</h5>
{{ sections }} {{page}} {{slug}}
Отделение теоретической (структурной) и прикладной лингвистики (ОТиПЛ, ранее ОСиПЛ) существует на филологическом факультете МГУ с 1960 года.

ОТиПЛ — один из ведущих учебных и исследовательских центров лингвистической науки в России. Здесь готовят высококлассных специалистов в различных областях современной лингвистики.
              <h5>Программа обучения</h5>

Студенты ОТиПЛа получают фундаментальные знания по вопросам общей теории языка, современных прикладных направлений языкознания, математических методов лингвистического анализа, наиболее важных смежных дисциплин. В свете этих знаний преподаются и важнейшие аспекты русского языка. -->

            </div>
            {% if page.has_news %}
            <div class="col-md-4">
            <div class="well"> <h4 class="text-center">Новости</h4>
               {{news|safe}}
               <!-- Сегодня ничего не произошло, вообще. Давно ничего не происходило.
                              Сегодня ничего не произошло, вообще. Давно ничего не происходило.
                                             Сегодня ничего не произошло, вообще. Давно ничего не происходило.
                                                            Сегодня ничего не произошло, вообще. Давно ничего не происходило.
                                                                           Сегодня ничего не произошло, вообще. Давно ничего не происходило. -->
            </div>
            </div>
            {% endif %}
          </div>
          <div class='row'>
              <div class="col-md-12">
              {% if files %}
              <h6> Прикрепленные файлы</h6>
              {% for f in files %}
                <!-- {{ f }} -->

                <a href="{{ f.url|safe }}" class="btn btn-default"><span class="glyphicon glyphicon-save"></span> {{f.name}}</a>
              {% endfor%}
            {% endif %}
            </div>
          </div>
        </div>
        </div>
    <div id="footer">
    <div class="container">
    <div class="row">
<div class="well well-sm col-md-4 text-muted"><small>
        119991, Москва, Ленинские горы, ГСП-1, <br>
МГУ имени М. В. Ломоносова,<br>
1-й корпус гуманитарных факультетов (1-й ГУМ), <br>
филологический факультет<br>
Тел.: +7 (495) 939-32-77, E-mail: dekan@philol.msu.ru</small>
</div>
      </div>
      </div>
    </div>
        <!-- </div> -->
      </body>
</html>

otipl/templates/main/index.html
{% extends "main/base.html" %}

otipl/templates/main/otipl.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8">
	    <title>Кафедра теоретической и прикладной лингвистики</title>
	    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
	    <style type="text/css">
		    html,
			body {
			    height: 100%;
				/* The html and body elements cannot have any padding or margin. */
			}

			/* Wrapper for page content to push down footer */
		    #wrap {
				min-height: 100%;
			    height: auto !important;
			    height: 100%;
			    /* Negative indent footer by its height */
			    margin: 0 auto -60px;
			    /* Pad bottom by footer height */
			    padding: 0 0 60px;
			}
	    </style>
	</head>
	<body style="background-color: LightCyan;">
        <script src="{% static "js/jquery.js" %}"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>
		<div id="wrap">
			<div class="row" style="background: url('{% static "images/letters2.jpg" %}') no-repeat right bottom; background-size: contain; background-color: white; margin: 0px">
				<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
	  				<img src="{% static "images/logo.jpg" %}" class="img-responsive" style="padding: 5px; width: 80%;" alt="Responsive image">
				</div>
			    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8" style="background-color: White;">
				    <h5>Московский государственный университет</h5>
			        <h3>Филологический факультет</h3>
			        <h2>КАФЕДРА ТЕОРЕТИЧЕСКОЙ И ПРИКЛАДНОЙ ЛИНГВИСТИКИ</h2>
			    </div>
			    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1" style="padding: 10px 0px; text-align:center">
					<form role="form">
					    <div class="form-group" style="margin: 5px 0px">
					      <input type="email" class="form-control input-sm" placeholder="E-mail">
					    </div>
					    <div class="form-group" style="margin: 5px 0px">
						    <input type="password" class="form-control input-sm"  placeholder="Пароль">
					    </div>
					    <button type="submit" class="btn btn-default btn-sm" >
					    	<span class="glyphicon glyphicon-log-in"></span>
					    </button>
					</form>
			    </div>
			    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
					<img src="{% static "images/flag_rus.png" %}" style="width: 20px; margin: 15px 2px">
				    <img src="{% static "images/uk_flag.png" %}" style="width: 20px; margin: 15px 2px">
			    </div>
			</div>
	        <nav class="navbar navbar-default" role="navigation" style="background-color: #ADD8E6; border-color: #000000;">
	            <div class="collapse navbar-collapse text-center">
	                <ul class="nav navbar-nav">
                    {% for sec in sections %}
	                    <li class="dropdown {% if page and page.subsection.section == sec %} active {% endif %}">
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ sec.name }}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
	                        {% for subsec in sec.page_set.all %}
	                            <li><a href="/{{subsec.slug}}">{{ subsec.name }}</a></li>
	                        {% endfor %}
		                    </ul>
	                    </li>
	                {% endfor %}
	                {% for sec in free_sec %}
	                    <li class="{% if page and page == sec %} active {% endif %}"><a href="/{{sec.slug}}">{{sec.name}}</a></li>
	                {% endfor %}                       
		            </ul>
	                <form class="navbar-form navbar-right" role="search" style="padding: 0px">
					    <div class="form-group"	>
						    <input type="text" class="form-control" placeholder="Поиск">
						</div>
					        <button class="btn btn-default" type="button">
					        	<span class="glyphicon glyphicon-search"></span>
					        </button>

						
				    </form>
	            </div>         
	        </nav>
	        <div class="container">
	        	<div class="row" >
	        	    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
		        		<div class="well" style="min-height:400px; border-color: Black; background: url('{% static "images/omega.jpg" %}') no-repeat right bottom; background-size: 100%; background-color: #CBCDC9; padding: 10px">
					        <ul class="nav nav-pills nav-stacked">
		                    {% for p in left_bar %}
			                    <li class="{% if page and page == p %} active {% endif %}">
			                        <a href="/{{p.slug}}">{{ p.name }}</a>
			                    </li>
			                {% endfor %}
					        </ul>

		        		</div>
	        		</div>
	        		<div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
	        		    <div class="well" style="min-height:400px; background-color: Moccasin; border-color: Black;" >
	        		    	{{page.content|safe}}
    		    	        <div class='row' style="  vertical-align: bottom;">
				                <div class="col-md-12">
				                {% if files %}
					                <h6> Прикрепленные файлы</h6>
					                {% for f in files %}
					                <a href="{{ f.url|safe }}" class="btn btn-default">
					                	<span class="glyphicon glyphicon-save"></span> {{f.name}}
				                	</a>
					                {% endfor%}
					            {% endif %}
					            </div>
				            </div>
	        		    </div>
	        		</div>
	        		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
	        			{% if get_pass_button %}
	        			<div style="text-align:center;">
		        		    <a href="/{{ get_pass_button.slug }}" role="button" class="btn btn-info btn-large" style="margin: 0px 0px 20px 0px;">
		        		    Как получить пропуск
		        		    </a>
		        		</div>
		        		{% endif %}
	        		    <div class="well" style="background-color: SkyBlue; min-height:346px; border-color: Black">
		        		    <div style="text-align:center;">
		        		    	<h2 class="pull-center" style="margin: 0px 0px 20px 0px;">Новости</h2>
		        		    	
		        		    </div>
		        		    {{news|safe}}
	        		    </div>
	        		</div>
	        	</div>
	        </div>
		</div>
        <div id="footer">
		    <!-- <div class="container"> -->
			    <div class="row" style="padding: 0px; margin: 0px">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-muted" style="padding: 0px; margin: 0px">
						<div class="well" style="margin: 0px; padding: 5px">
							<small>
							    <div class="row" style="padding: 0px; margin: 0px">
									<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 text-muted" style="padding: 0px; margin: 0px">								
								        119991, Москва, Ленинские горы, ГСП-1,
										МГУ имени М. В. Ломоносова,<br>
										1-й корпус гуманитарных факультетов (1-й ГУМ),
										филологический факультет
									</div>
									<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-muted" style="padding: 0px; margin: 0px">
										Тел.: +7 (495) 939-32-77,<br>
										E-mail: dekan@philol.msu.ru
									</div>
							</small>
						</div>
					</div>
			    </div>
		    <!-- </div> -->
	    </div>

	</body>
</html>